#!/bin/bash

# -----------------------------------------
# K8s
# -----------------------------------------
ibmcloud login

# Get ibmcloud Kubernetes configs so that we can run
# kubectl from our own computer.
ibmcloud ks cluster ls  # Suppose your cluster name is nsustain
ibmcloud ks cluster config --cluster nsustain --admin

# Get all available K8s resources with their aliases
kubectl api-resources

# Run bash inside the pod
kubectl exec -it [podName] /bin/bash

kubectl run test --image=soobinrho/test:0.1 --port=30870 --env="NGINX_PORT=30870"

# Run k9s to monitor k8s
docker run --rm -it -v ~/.kube/config:/root/.kube/config quay.io/derailed/k9s

kubectl apply -f cloudflared.yaml
kubectl delete -f cloudflared.yaml

# deployment in short = deploy
kubectl delete --all deploy

# services in short = svc
kubectl delete --all svc


# "To decide how to handle updates, StatefulSets use an update
# strategy defined in spec: updateStrategy. There are two
# strategies, OnDelete and RollingUpdate"
# Source:
#   https://cloud.google.com/kubernetes-engine/docs/concepts/statefulset#updating_statefulsets

# Rollback to the previous deployment
kubectl rollout undo deployment/abc

# Check the rollout status of a daemonset
kubectl rollout status daemonset/foo

# Restart a deployment
kubectl rollout restart deployment/abc

# "Create a Service before its corresponding backend workloads (Deployments or ReplicaSets), and before any workloads that need to access it."
# Source:
#   https://kubernetes.io/docs/concepts/configuration/overview/

# How to use hostPort
# Source:
#   https://alesnosek.com/blog/2017/02/14/accessing-kubernetes-pods-from-outside-of-the-cluster/
apiVersion: v1
kind: Pod
metadata:
  name: influxdb
spec:
  containers:
    - name: influxdb
      image: influxdb
      ports:
        - containerPort: 8086
          hostPort: 8086

# How to add Redis on K8s
# Source:
#   https://cloud.google.com/kubernetes-engine/docs/tutorials/guestbook

# How to encode / decode base64 for K8s secrets
# Source:
#   https://www.cloudytuts.com/tutorials/kubernetes/how-to-base64-encode-kubernetes-secrets/
echo -n 'super-secret-password' | base64
echo -n 'c3VwZXItc2VjcmV0LXBhc3N3b3Jk' | base64 --decode
