#!/bin/bash

# This file stores docker commands I used frequently
# for learning purposes.

# ------------------------------------------
# https://docs.docker.com/get-started/
# ------------------------------------------

# Run an Ubuntu
docker run --rm -itv hello_world:/hello_world ubuntu

# Run an Ubuntu and don't exit automatically
docker run --rm -dv hello_world:/hello_world ubuntu /bin/bash -c "tail -f /dev/null"

# Run bash inside a container
docker exec -it <container_name> /bin/bash

# ------------------------------------------
# HaashiCorp Vault
# ------------------------------------------

# Start a development server
docker run --rm -p 8200:8200 --cap-add=IPC_LOCK -it vault
