#! /bin/bash

# This file runs whenever we run the Docker nsustain/flarum image.
# The purpose of this file is to set the ENTRYPOINT for Docker.

# $DEBUG, as well as all other env variables are set on compose.yaml
INSTALL_FILE_DIR="/flarumInstall.yaml"

sed -i "s/DEBUG/$DEBUG/g" $INSTALL_FILE_DIR
sed -i "s|FORUM_URL|$FORUM_URL|g" $INSTALL_FILE_DIR
sed -i "s/DB_HOST/$DB_HOST/g" $INSTALL_FILE_DIR
sed -i "s/DB_PORT/$DB_PORT/g" $INSTALL_FILE_DIR
sed -i "s/DB_NAME/$DB_NAME/g" $INSTALL_FILE_DIR
sed -i "s/DB_USER/$DB_USER/g" $INSTALL_FILE_DIR
sed -i "s/DB_PASS/$DB_PASS/g" $INSTALL_FILE_DIR
sed -i "s/DB_PREF/$DB_PREF/g" $INSTALL_FILE_DIR
sed -i "s/FLARUM_ADMIN_USER/$FLARUM_ADMIN_USER/g" $INSTALL_FILE_DIR
sed -i "s/FLARUM_ADMIN_PASS/$FLARUM_ADMIN_PASS/g" $INSTALL_FILE_DIR
sed -i "s/FLARUM_ADMIN_MAIL/$FLARUM_ADMIN_MAIL/g" $INSTALL_FILE_DIR
sed -i "s/FLARUM_TITLE/$FLARUM_TITLE/g" $INSTALL_FILE_DIR

# Wait until mariadb boots up.
# What this means is that it first waits 10 seconds
# and then exits as soon as mariadb is connected, but if not,
# it waits for 20 seconds maximum.
sleep 10
timeout 5 && mariadb --host mariadb 2> /dev/null
if [ $? -ne 0 ]
then
 	timeout 5 mariadb --host mariadb 2> /dev/null
fi

php flarum install -f $INSTALL_FILE_DIR

# Flarum is served by both php-fpm and nginx.
# When http request comes in, nginx first receives it;
# php-fpm8 handles php files; and then finally nginx serves.
php-fpm8
nginx

# DEBUG: for do not quit
tail -f /dev/null

# -------------------------------
# Migrate everytime the image is run.
# Source:
#   https://discuss.flarum.org/d/31640-flarum-setup-with-preset-config-file-and-use-env/9
# if [[ -f "config.php" ]]; then
#   php flarum migrate
#   php flarum cache:clear
#   php flarum assets:publish
# else
#   php flarum install -f install.yml
# fi
#
# # Reset permissions
# chown -R www-data:www-data /var/www/storage/ && chmod -R g+w /var/www/storage/ && chmod -R 755 /var/www/storage/
#
# # Start apache
# apache2-foreground
# -------------------------------
