#!/bin/bash

# -----------------------------------------------------------------
# We found these aliases useful for Docker. You don't have to use 
# these. We include these aliases here just for your information.
# You can choose to use them, if you'd like.
#
# HOW TO USE THESE ALIASES FOR JUST ONE SESSION
#   cd nsustain.com/src/docker/optional
#   source userful-docker-aliases
#
# HOW TO PERMANENTLY ADD THESE ALIASES TO YOUR DOTFILE
#   cd nsustain.com/src/docker/optional
#   cat userful-docker-aliases >> ~/.bashrc
# -----------------------------------------------------------------

# Remove all docker containers
alias dockerrm="docker ps -aq | xargs docker stop | xargs docker rm"

# Remove all docker volumes
# [WARNING] Always be careful when deleting volumes.
# All your website data is store in these volumes.
alias dockervolumerm="docker volume ls -q | xargs docker volume rm"

# Remove all docker images
alias dockerrmi="docker images -q | xargs docker rmi -f"