#!/bin/bash

# ----------------------------------------------------------------
# This script is for issuing https / SSL certificates.
#
# HOW TO USE THIS SCRIPT
#   cd nsustain.com/src/docker/useful-bash-helper-scripts
#   sudo chmod +x certbot-get-ssl
#   ./certbot-get-ssl
# ----------------------------------------------------------------

# This line uses certbot to issue a certificate.
# Source:
#   https://eff-certbot.readthedocs.io/en/stable/install.html#running-with-docker
docker run -it --rm -v /etc/letsencrypt:/etc/letsencrypt -v /var/lib/letsencrypt:/var/lib/letsencrypt certbot/certbot certonly
