all: build

build: 
	@echo "Without @ sign, this whole statement gets printed as well"
	@echo "Also, the first target is the default target."
	@echo "For example, here, 'all', 'build', and 'clean' are targets."
	@touch test1234321.txt

clean:
	rm test1234321.txt
